### ISSUE TITLE
Documentation: Permission Denied

### ISSUE THREAD

**Issue by M3ssman** [GovDataOfficial/OGD-1.1#1]
Hello,

clicking on the [Domain Model link](http://docs.ckan.org/en/ckan-1.8/domain-model.html) yields a "Permission Denied" Message. 
So, please, where can more Information on this Topic be found?

**Comment by akuckartz** [comment]
That is an issue regarding ckan.org.

See https://www.govdata.de/web/guest/standardisierung for future plans of OGD which are based on DCAT and DCAT-AP.

**Comment by M3ssman** [comment]
Ah, very well. Thanks for your reply.
Anyway, it would be a good idea to remove the dead link to avoid an inconsistent documentation state.
